GET http://localhost:3003/

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Test Blog 2",
    "author": "Testboy",
    "url": "www.testblog.com",
    "user": "686646dcee02f3417c3a1124",
    "likes": 0
}

###
PUT http://localhost:3003/api/blogs/68629d1d49aa9203de2ed3da
content-type: application/json

{
    "title": "Test Blog 2",
    "author": "Testperson",
    "url": "www.testblog.com",
    "likes": 0
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/users/
Content-Type: application/json

{
    "username": "Pololo",
    "name": "Paul GT",
    "password": "password"
}